include: package:lints/recommended.yaml

analyzer:
  exclude:
    - test/fixtures/**

linter:
  rules:
    - prefer_final_locals
    - prefer_const_constructors
    - prefer_const_declarations
    - avoid_print
    - require_trailing_commas
